sudo: required
services:
  - docker

before_install:
  - docker build -t syedshameersarwar/react-docker -f Dockerfile.dev .

script:
  - docker run syedshameersarwar/react-docker npm run test -- --coverage
